version: "3.3"
services:
  test-db:
    image: mysql:8
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
  dev-db:
    image: mysql:8
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dev
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
  runner:
    image: node:lts
    user: ${CURRENT_UID}
    working_dir: /home/node
    volumes:
      - ./:/home/node
    depends_on:
      - test-db